export { default as Sidebar } from "./sidebar/Sidebar"
export { default as Admin } from "./admin/Admin"
export { default as AddModal } from "./add-modal/Add-modal"
export { default as BarcodeModal } from "./bar-code-modal/BarCodeModal"
export { default as Table } from "./table/Table"
export { default as Storage } from "./storage/Storage"
export { default as Main } from "./main/Main"
export { default as Login } from "./login/Login"
export { default as Seller } from "./seller/Seller"
export {default as Salesman} from "./salesman/Salesman"